### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by zaminsirat** [Delphi-BFT/tool#35]
Great work! 
I thought the simulator would automatically generate plots, but it seems we need to do that manually by using the stdout log files in the hosts folder and create :
```
- name: HotStuff-l10-lat
  values:
    - x: '4'
      y: '84.178'
    - x: '8'
      y: '85.734'
    - x: '16'
      y: '86.6358'
    - x: '32'
      y: '88.4466'
    - x: '64'
      y: '92.4532'
    - x: '128'
      y: '106.0368'
  style:
    pointStyle: star
    pointBorderColor: '#8e5ea2'
    borderColor: '#8e5ea2'
```
